# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# themes in ~/.oh-my-zsh/themes/
export ZSH_THEME="erikbehrends"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"
export DISABLE_UPDATE_PROMPT="true"

if [ "$OSTYPE" = "linux-gnu" ]; then
  plugins=(git)
  bindkey "^[[1;3C" forward-word
  bindkey "^[[1;3D" backward-word
else
  plugins=(brew gem git)
fi

source $ZSH/oh-my-zsh.sh

cdpath=($HOME/Documents/Dev)

# rvm 
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.

export PATH=/usr/local/bin:$HOME/bin:$PATH

export EDITOR=vim
