# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# themes in ~/.oh-my-zsh/themes/
export ZSH_THEME="erikbehrends"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"
export DISABLE_UPDATE_PROMPT="true"

if [ "$OSTYPE" = "linux-gnu" ]; then
  plugins=(git)
  bindkey "^[[1;3C" forward-word
  bindkey "^[[1;3D" backward-word
else
  bindkey '^[^[[C' emacs-forward-word
  bindkey '^[^[[D' emacs-backward-word
  plugins=(brew gem git)
fi

source $ZSH/oh-my-zsh.sh

cdpath=($HOME/Documents/Dev)

export PATH=/usr/local/bin:/usr/local/sbin:$HOME/bin:$PATH

if [[ -e "$HOME/.zshrc.local" ]]; then 
  source $HOME/.zshrc.local
fi

[[ -f `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

export EDITOR=vim

export LESS="-RX"

# for Umlauts etc in file names
export LC_CTYPE=UTF-8

alias grm='git rebase master'
alias gh="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --all"
alias gsf='git show --name-only'
